//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeAttendance.DAL.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeeAttendenceEntities : DbContext
    {
        public EmployeeAttendenceEntities()
            : base("name=EmployeeAttendenceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminSignUp> AdminSignUps { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<EmployeeDetail> EmployeeDetails { get; set; }
        public virtual DbSet<LoginPage> LoginPages { get; set; }
        public virtual DbSet<LoginTime> LoginTimes { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<UserLoginDetail> UserLoginDetails { get; set; }
    }
}
